name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java: [17-jdk, 21-jdk]
    runs-on: ubuntu-24.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v2
      - run: ./gradlew build publishToMavenLocal --stacktrace --warning-mode fail